# Generated by Django 3.2 on 2021-04-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNeeds', '0002_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='img',
            field=models.ImageField(upload_to='Brands_Images_Images/'),
        ),
    ]
