# Generated by Django 3.2 on 2021-04-28 18:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNeeds', '0003_alter_brands_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='dBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Brand Name')),
                ('img', models.ImageField(upload_to='DailyNeed/BrandName_Images/')),
                ('url', models.SlugField(blank=True, max_length=255, unique=True)),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DailyNeeds.producttype')),
            ],
            options={
                'verbose_name': 'Brand',
                'db_table': 'dBrands',
            },
        ),
        migrations.CreateModel(
            name='ProductsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='DailyNeed/Products/')),
                ('img2', models.ImageField(upload_to='DailyNeed/Products/')),
                ('img3', models.ImageField(upload_to='DailyNeed/Products/')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DailyNeeds.producttype')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DailyNeeds.dbrands')),
            ],
            options={
                'verbose_name': 'Product Detail',
                'db_table': 'ProductsDetails',
            },
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
    ]
