# Generated by Django 3.2 on 2021-04-27 18:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Brand Name')),
                ('img', models.ImageField(upload_to='Cosmetics/BrandName_Images/')),
                ('url', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'db_table': 'BrandName',
            },
        ),
        migrations.AlterField(
            model_name='producttype',
            name='img',
            field=models.ImageField(upload_to='Cosmetics/Product_Type_Images/'),
        ),
        migrations.CreateModel(
            name='ProductsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='Cosmetics/Products/')),
                ('img2', models.ImageField(upload_to='Cosmetics/Products/')),
                ('img3', models.ImageField(upload_to='Cosmetics/Products/')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cosmetics.producttype')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cosmetics.brandname')),
            ],
            options={
                'verbose_name': 'Product Detail',
                'db_table': 'ProductsDetail',
            },
        ),
        migrations.AddField(
            model_name='brandname',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cosmetics.producttype'),
        ),
    ]
