# Generated by Django 3.2 on 2021-05-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetics', '0002_auto_20210428_0027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductType',
            new_name='CosmeticsProductType',
        ),
    ]
