# Generated by Django 3.2 on 2021-05-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOwnerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerName', models.CharField(max_length=100)),
                ('ownerCompanyname', models.CharField(max_length=100)),
                ('ownerDesignation', models.CharField(max_length=100)),
                ('ownerBusinessLocation', models.CharField(max_length=100)),
                ('ownerBusinessType', models.CharField(max_length=11)),
                ('ownerAddress', models.CharField(max_length=100)),
                ('ownerCity', models.CharField(max_length=100)),
                ('ownerState', models.CharField(max_length=100)),
                ('ownerZip', models.IntegerField()),
                ('ownerEmail', models.CharField(max_length=100)),
                ('ownerPhone', models.CharField(max_length=100)),
                ('ownerFax', models.CharField(max_length=100)),
                ('ownerWebsite', models.CharField(max_length=100)),
                ('ownerMessage', models.TextField()),
            ],
        ),
    ]
