# Generated by Django 3.2 on 2021-05-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_clientownerform'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOwnerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.CharField(max_length=100)),
                ('EmployeeCompanyname', models.CharField(max_length=100)),
                ('EmployeeDesignation', models.CharField(max_length=100)),
                ('EmployeeBusinessLocation', models.CharField(max_length=100)),
                ('EmployeeBusinessType', models.CharField(max_length=11)),
                ('EmployeeAddress', models.CharField(max_length=100)),
                ('EmployeeCity', models.CharField(max_length=100)),
                ('EmployeeState', models.CharField(max_length=100)),
                ('EmployeeZip', models.IntegerField()),
                ('EmployeeEmail', models.CharField(max_length=100)),
                ('EmployeePhone', models.CharField(max_length=100)),
                ('EmployeeFax', models.CharField(max_length=100)),
                ('EmployeeWebsite', models.CharField(max_length=100)),
                ('OwnerName', models.CharField(max_length=100)),
                ('OwnerDesignation', models.CharField(max_length=100)),
                ('OwnerAddress', models.CharField(max_length=100)),
                ('OwnerCity', models.CharField(max_length=100)),
                ('OwnerState', models.CharField(max_length=100)),
                ('OwnerZip', models.IntegerField()),
                ('OwnerEmail', models.CharField(max_length=100)),
                ('OwnerPhone', models.CharField(max_length=100)),
                ('EmployeeMessage', models.TextField()),
            ],
        ),
    ]
