# Generated by Django 3.2 on 2021-04-22 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Brand Name')),
                ('img', models.ImageField(upload_to='Brands_Images/')),
                ('url', models.SlugField(blank=True, max_length=255, unique=True)),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electronics.producttype')),
            ],
        ),
    ]
