# Generated by Django 3.2 on 2021-04-23 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0002_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Model Name')),
                ('url', models.SlugField(blank=True, max_length=255, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electronics.brands')),
            ],
        ),
    ]
