# Generated by Django 3.2 on 2021-04-23 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0003_modelno'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelno',
            name='Type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Electronics.producttype'),
            preserve_default=False,
        ),
    ]
