# Generated by Django 3.2 on 2021-04-23 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0004_modelno_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Brand'},
        ),
        migrations.AlterModelTable(
            name='brands',
            table='Brands',
        ),
    ]
