# Generated by Django 3.2 on 2021-04-25 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0005_auto_20210424_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelno',
            old_name='url',
            new_name='uid',
        ),
    ]
