# Generated by Django 3.2 on 2021-04-26 10:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Garments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Brand Name')),
                ('img', models.ImageField(upload_to='BrandsName_Images/')),
                ('url', models.SlugField(blank=True, max_length=255, unique=True)),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garments.producttype')),
            ],
            options={
                'verbose_name': 'Brand',
                'db_table': 'BrandsName',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='Garments/Products/')),
                ('img2', models.ImageField(upload_to='Garments/Products/')),
                ('img3', models.ImageField(upload_to='Garments/Products/')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garments.producttype')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garments.brandsname')),
            ],
            options={
                'verbose_name': 'Product Detail',
                'db_table': 'ProductDetail',
            },
        ),
    ]
